package:
    name: pyg-sql
    version: 0.0.40

source:
    path: ../src
	
build:
    include_recipe: False
    number: 0
    noarch: python

requirements:
    build:
        - pyg-base          >=0.0.22
        - pyg-encoders      >=0.0.5
        - sqlalchemy        >=1.3.13
        - sqlalchemy-utils  >=0.36.5
    run:
        - pyg-base          >=0.0.22
        - pyg-encoders      >=0.0.5
        - sqlalchemy        >=1.3.13
        - sqlalchemy-utils  >=0.36.5
        
about:
    home: https://github.com/gityoav/pyg-sql
    license: GNU