package:
    name: pyg-sql
    version: 0.0.1

source:
    path: ../src
	
build:
    include_recipe: False
    number: 0
    noarch: python

requirements:
    build:
        - pyg-base          >=0.0.3
        - pyg-encoders      >=0.0.1
        - sqlalchemy        >=1.4
        - sqlalchemy-utils  >=0.38.2
    run:
        - pyg-base          >=0.0.3
        - pyg-encoders      >=0.0.1
        - sqlalchemy        >=1.4
        - sqlalchemy-utils  >=0.38.2
        
about:
    home: https://github.com/gityoav/pyg-sql
    license: GNU